# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2,TLSv1.3 -Djavax.net.ssl.trustStoreType=KeychainStore
org.gradle.java.home=/Users/taesupyoon/Library/Java/JavaVirtualMachines/corretto-17.0.13/Contents/Home
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
newArchEnabled=false
hermesEnabled=true
